### PR TITLE
MaxQuant wrapper

### PR DESCRIPTION
**Pull request by MateusBellomo**

### CODE REVIEW

**Comment by bgruening** [comment]
Why do you want to merge this? And why is it called MaxQuant? :)

**Comment by MateusBellomo** [comment]
Sorry...I've made some changes in the MaxQuant wrapper and John told me to do a pull request. I'm not familiar with github and I don't know how to do that.

**Comment by bgruening** [comment]
You have a cloned repository? And you have commited your changes to a local new branch?

**Comment by MateusBellomo** [comment]
No, I don't have a cloned repository. And I don't know how to do that.
I also didn't commited my changes. I think would be better wait for my advisor helps me to do that before I accidentally screw up something. =)

**Comment by bgruening** [comment]
Either this or you can mail me your change I will try to put them in.

**Pull request closed without merging**
