### PR TITLE
New version for msgf+: 20170721

### PR DESCRIPTION
**Pull request by glormph**
I saw that @blankclemens had updated bioconda which meant I didnt have to do that myself 👍 Thanks and here comes the galaxy tool update.

### CODE REVIEW

**Comment by bgruening** [comment]
@chambm can you please look at this. The test files could not be found. I guess the link is broken and it points to bumbershoot.

**Comment by chambm** [comment]
Sorry I didn't see this ping. Just made another PR to fix it.

**Comment by bgruening** [comment]
@glormph restarted the PR. Can you update the test data please?

**Comment by glormph** [comment]
Done! Thanks @bgruening and @chambm!

**Comment by bgruening** [comment]
Neat! Thanks!

**Pull request merged**
