### PR TITLE
pathwaymatcher: add coreutils

### PR DESCRIPTION
**Pull request by bernt-matthias**
- to allow for `mv -t`
- also remove unnecessary redirections

### CODE REVIEW

**Comment by bgruening** [comment]
Please bump the version number :)

We are waiting until testing is in place, do we?

**Comment by bernt-matthias** [comment]
looks good to me . version number is bumped :)

**Comment by bgruening** [comment]
Can you please check that this is also getting uploaded? We probably need to set credentials, left?

**Comment by bgruening** [comment]
Also I guess we need to update the travis badge on the main readme when this is working.

**Comment by bernt-matthias** [comment]
yep. credentials are missing: https://github.com/galaxyproteomics/tools-galaxyp/runs/565889196?check_suite_focus=true 

we need `tts_api_key` and `ts_api_key` .. then we can restart the workflows listen in the Actions tab.

**Comment by bgruening** [comment]
Did this yesterday evening.

**Pull request merged**
