### PR TITLE
msdata converter wiff file support and peptideshaker bug fixes

### PR DESCRIPTION
**Pull request by iracooke**

### CODE REVIEW

**Comment by iracooke** [comment]
Will leave this to Trevor to JJ to approve since most of the stuff in this PR is from JJ

**Comment by trevor** [comment]
@iracooke Hi Ira, what is this PR about? Aren't these commits already in master?

**Comment by iracooke** [comment]
@trevor I don't think the exact commits are in master .. at least not by looking at the commit hash.

**Comment by trevor** [comment]
I'm looking here: https://github.com/galaxyproteomics/tools-galaxyp/commits/master

Could you tell me which hashes differ?

**Comment by iracooke** [comment]
@trevor Not sure how I missed that! But it seems very weird to me.  Why does github think those commits need merging again?  If you look at the graph view it shows branch peptideshaker-temp not having ever been merged back into master.

**Comment by trevor** [comment]
Not sure how github generates it's graph, I'm guessing it's getting confused by our mix of non-fastforward and fastforward merges, the graph looks different in `gitk` and `tig`.

**Comment by iracooke** [comment]
Yeah .. somethings definitely a bit wrong.  When I diff the two branches on the command line it just shows the one commit.

git log master..peptideshaker-temp
commit 3175e3c589ddcd0578efdb6e30453f98c528e52b
Author: Ira Cooke <iracooke@gmail.com>
Date:   Fri Mar 13 19:47:50 2015 +1100

    Add Tide search engine. Default to Off

**Comment by iracooke** [comment]
Despite the weirdness I think this merge is safe to do.  I have just tried in on the command-line and the only actual change that gets made is related to my recent commit (the only one that actually differs).

**Pull request merged**
