### PR TITLE
searchgui home fix and enzyme list update

### PR DESCRIPTION
**Pull request by bernt-matthias**
- fixes https://github.com/galaxyproteomics/tools-galaxyp/issues/293
- removes enzymes that are not supported anymore. 
- adds OOM regex checks to stdio
- removed unnecessary default enzyme (since there was a typo in the command block the option never worked anyway, so we can savely remove it)

Ping @CarlosHorro, @hbarsnes. Thanks for your help .. could you have a look?

The second part of the PR solves the problem described below: 

I noticed that many of the parameters to -enzyme parameter of IdentificationParametersCLI do not work at the moment, e.g. "Trypsin, no P rule". I guess the options are wrong in some cases, "Trypsin (no P rule)" seems to work. 

The command line help mentions:
- EnzymesCLI, but I could not find it. 
- the possibility give a comma separated list of enzymes which does not work if there are commas in the enzyme names
- also the example "Trypsin, Glu-C" does not work .. actually gives an exception

A fixed the one enzyme that our users interested in at the moment.

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Thanks a lot for your comments. I updated the list of enzymes.

**Comment by bernt-matthias** [comment]
again the fatal_oom problem

**Comment by bernt-matthias** [comment]
wondering why the wrong output name did work... I tested and noticed that any name con be used. Is this because it's a single output?

**Comment by bgruening** [comment]
@bernt-matthias sorry I did not get your last comment? Can you explain this more?

**Comment by bgruening** [comment]
Thanks all!

**Comment by bernt-matthias** [comment]
> sorry I did not get your last comment? Can you explain this more?

Sure I was wondering why the version before 
https://github.com/galaxyproteomics/tools-galaxyp/pull/312/commits/e238bae9ddea533533a2ccdf7703bdfc7124cf0a

could be tested successfully with planemo. Apparently the name of the output did not matter at all.

**Comment by bgruening** [comment]
Yes, please. Planemo can and should be a lot smarter about variable-names and their existence.

**Comment by bernt-matthias** [comment]
done

**Pull request merged**
