### PR TITLE
openms: also detect oom for C++ tools

### PR DESCRIPTION
**Pull request by bernt-matthias**
I remember that agressive error checkking is not an option, so I added only this one.

### CODE REVIEW

**Comment by bgruening** [comment]
Do you remember why its not an option?

**Comment by bernt-matthias** [comment]
Seems that we had it before https://github.com/galaxyproteomics/tools-galaxyp/pull/368 and reverted https://github.com/galaxyproteomics/tools-galaxyp/pull/399#discussion_r347131860

**Comment by bgruening** [comment]
> Seems that we had it before #368 and reverted [#399 (comment)](https://github.com/galaxyproteomics/tools-galaxyp/pull/399#discussion_r347131860)

Uha, I remember. Damn!

**Review by bgruening — APPROVED** [review]

**Comment by bernt-matthias** [comment]
Forgot to bump. Fixed.

**Pull request merged**
