### PR TITLE
searchgui, peptideshaker: version bump

### PR DESCRIPTION
**Pull request by bernt-matthias**
fixes https://github.com/compomics/searchgui/issues/192

@CarlosHorro @hbarsnes : just to be sure I would like to ask if there are also no changes to the options of the command line parameters (eg new defauls or new choices)?

### CODE REVIEW

**Comment by CarlosHorro** [comment]
Hi Matthias, just to confirm that there are no new options in the command line params.

**Comment by bernt-matthias** [comment]
Cool. Then I think the package could be merged. Looking forward to test it on our Galaxy. 

Just for your information, we needed to change the conda package a bit. For some reason the searchgui package now needed a C-compiler for building and therefor we also needed to remove noarch.

**Comment by bernt-matthias** [comment]
or this one https://github.com/galaxyproteomics/tools-galaxyp/pull/326 .. damn I should have checked :)

**Comment by CarlosHorro** [comment]
I don't understand the point related to the conda package... the new version was merged without any extra addition...

**Comment by bernt-matthias** [comment]
In requirements we added: 

```
build:
    - {{ compiler('c') }}
```

and in `build` the line

```
  noarch: generic
```

was removed

See these commits: 

https://github.com/bioconda/bioconda-recipes/pull/12136/commits/06fb92289607c71d675c5c6899fffe47d29101fe
https://github.com/bioconda/bioconda-recipes/pull/12136/commits/8ebc18ea7e893195215b6dd42c44229662ecd238

**Pull request closed without merging**
