### PR TITLE
msconvert: improve error detection

### PR DESCRIPTION
**Pull request by bernt-matthias**
msconvert wrote an incomplete file had exit code 0 and wrote the following to stderr. I think this should be a tool error

```
000d:err:menubuilder:init_xdg error looking up the desktop directory
0037:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0037:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0037:err:ole:apartment_createwindowifneeded CreateWindow failed with error 183
0037:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0037:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
000b:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
000b:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0035:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0035:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0035:err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\mscoree.dll" (error=80)
003f:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
003f:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Could not load wine-gecko. HTML rendering will be disabled.
0044:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0044:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0044:err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\mscoree.dll" (error=80)
0046:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0046:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/tmp/7240861.1.usva28/tmp.YnNKW8MLfl' has been updated.
0009:err:combase:RoGetActivationFactory Failed to find library for L"Windows.Foundation.Diagnostics.AsyncCausalityTracer"
Error writing run 1 in "180714_NJ_Bastida_ALP195.raw":
[RawFileImpl::setCurrentController()] Instrument index not available for requested device
Parameter name: instrumentIndex
```

All the lower case `"error"` should be OK. But for sure we could use a more specific regex.

furthermore somehow the sudo output redirection did not work locally.
I hope that the current form covers all cases.

### CODE REVIEW

**Review by chambm — APPROVED** [review]
Note that this particular error is probably fixed in the newer msconvert version.

**Comment by bernt-matthias** [comment]
> Note that this particular error is probably fixed in the newer msconvert version.

This would be excellent.

**Comment by bernt-matthias** [comment]
If you rebase your branch tests should run now.

**Comment by bernt-matthias** [comment]
Damn, stdio regex is case insensitive.

**Comment by bgruening** [comment]
@bernt-matthias do we merge this or do we put both PRs together. I would like to keep tool versions low and would like to see a merged PR if possible. But if you need this quickly let me know.

**Comment by bernt-matthias** [comment]
I'm fine with cherry picking to https://github.com/galaxyproteomics/tools-galaxyp/pull/514. This is not solving the problem anyway .. just helps to detect it.

**Comment by bernt-matthias** [comment]
superseded by https://github.com/galaxyproteomics/tools-galaxyp/pull/514

**Pull request closed without merging**
