### PR TITLE
sync ci workflows with IUC

### PR DESCRIPTION
**Pull request by bernt-matthias**
- R linting
- updated actions
- planemo test uses --no_dependency_resolution

is ` github.repository_owner == 'galaxyproteomics'` correct?

### CODE REVIEW

**Comment by bgruening** [comment]
@bernt-matthias is it possible to create an own action based on this? So one single spot that we need to maintain?

**Comment by bernt-matthias** [comment]
Would be nice .. not sure if I can spend time on this now. An alternative might be a git submodule, or?

**Comment by bernt-matthias** [comment]
Also: if we would have an action then all repos still would need to have workflows and update the action's version ...

**Comment by bgruening** [comment]
submodules are usually hard to handle, I think actions and bumping versions are the way to go. Maybe you can open an issue on IUC so we can keep track. Thanks Matthias!

**Pull request merged**
