### PR TITLE
eggnog mapper: implement search and annotation phase as additional separate tools

### PR DESCRIPTION
**Pull request by bernt-matthias**
for rationale see README

TODO:

- [x] separate output options that apply only to annotation / search phase -> macros

### CODE REVIEW

**Comment by bgruening** [comment]
Having those 3 steps in one tool is not an option?

**Comment by bernt-matthias** [comment]
> Having those 3 steps in one tool is not an option?

I do not see how to map the steps to different destinations if implemented in one tool (dynamic destinations might be an option, but many sites use static destinations.. Like mine ;))

**Comment by bernt-matthias** [comment]
Btw. Linting failures are due to the missing updates of the tool-util package for 21.01. Any idea how to get this on the way?

**Comment by bernt-matthias** [comment]
> Having those 3 steps in one tool is not an option?

- eggnog_mapper.xml is still the monolithic tool 
- I just added two tools separating the search and annotation phase (as suggested by the docs https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5-to-v2.1.12#setting-up-large-annotation-jobs), which allows setting different number of CPUs and a memory for the two stages. It also allows for a better parallelization of the search phase by splitting the input into chunks (+ the parallelization provided by the underlying search tool).

Let my just add https://github.com/galaxyproteomics/tools-galaxyp/pull/727 to this PR ..

**Comment by bernt-matthias** [comment]
> Let my just add https://github.com/galaxyproteomics/tools-galaxyp/pull/727 to this PR ..

I reconsidered (because `--dbmem` was already handled here) and just left it as is. I'm happy to change to an entirely admin-controlled behavior, i.e. to use `--dbmem` only if the admin sets it as in https://github.com/galaxyproteomics/tools-galaxyp/pull/727

**Review by bgruening — APPROVED** [review]

**Pull request merged**
