### PR TITLE
Fix boolean to select bugs in msconvert

### PR DESCRIPTION
**Pull request by mvdbeek**
Fixes
```
NotFound: cannot find 'input_ident' while searching for 'data_processing.precursor_refinement.input_ident.ext'
  File "galaxy/jobs/runners/__init__.py", line 297, in prepare_job
    job_wrapper.prepare()
  File "galaxy/jobs/__init__.py", line 1256, in prepare
    ) = tool_evaluator.build()
  File "galaxy/tools/evaluation.py", line 588, in build
    global_tool_logs(self._build_command_line, config_file, "Building Command Line")
  File "galaxy/tools/evaluation.py", line 98, in global_tool_logs
    raise e
  File "galaxy/tools/evaluation.py", line 94, in global_tool_logs
    return func()
  File "galaxy/tools/evaluation.py", line 611, in _build_command_line
    command_line = fill_template(
  File "galaxy/util/template.py", line 115, in fill_template
    return fill_template(
  File "galaxy/util/template.py", line 115, in fill_template
    return fill_template(
  File "galaxy/util/template.py", line 115, in fill_template
    return fill_template(
  File "galaxy/util/template.py", line 115, in fill_template
    return fill_template(
  File "galaxy/util/template.py", line 115, in fill_template
    return fill_template(
  File "galaxy/util/template.py", line 115, in fill_template
    return fill_template(
  File "galaxy/util/template.py", line 115, in fill_template
    return fill_template(
  File "galaxy/util/template.py", line 115, in fill_template
    return fill_template(
  File "galaxy/util/template.py", line 115, in fill_template
    return fill_template(
  File "galaxy/util/template.py", line 115, in fill_template
    return fill_template(
  File "galaxy/util/template.py", line 123, in fill_template
    raise first_exception or e
  File "galaxy/util/template.py", line 87, in fill_template
    return unicodify(t, log_exception=False)
  File "galaxy/util/__init__.py", line 1196, in unicodify
    value = str(value)
  File "Cheetah/Template.py", line 1053, in __unicode__
    return getattr(self, mainMethName)()
  File "cheetah_DynamicallyCompiledCheetahTemplate_1712898486_6070771_49370.py", line 146, in respond
```

which broke in https://github.com/galaxyproteomics/tools-galaxyp/pull/748/commits/79947db04a2b8dc6db2465f71a9554a320cb5255.

@bebatut is there a chance that you could go over your recent EDAM related commits and see if this has happened elsewhere ?

### CODE REVIEW

**Comment by mvdbeek** [comment]
Really can't tell what the problem is here, step 5 is even missing from the log archive.

**Comment by mvdbeek** [comment]
Any chance we could merge this ? AFAICT the CI runs out of disk space. I've just fixed this again before I noticed I already came here to fix it.

**Comment by mvdbeek** [comment]
(https://sentry.galaxyproject.org/share/issue/13b4130f9c824f5c925daaec23865be8/)

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
I hope it gets deployed, lets see. Thanks @mvdbeek!

**Comment by mvdbeek** [comment]
I think this didn't get deployed @bgruening: https://toolshed.g2.bx.psu.edu/view/galaxyp/msconvert/545054b15d7c

**Comment by bgruening** [comment]
Manually uploaded. Thanks.

**Pull request merged**
