### PR TITLE
Update QuPath ROIsplitter to 0.2.1

### PR DESCRIPTION
**Pull request by npinter**
Includes a fix for filling ROIs of manually annotated data.

### CODE REVIEW

**Comment by bgruening** [comment]
> Exception: Test output defines nothing to check (e.g. must have a 'file' check against, assertions to check, metadata or checksum tests, etc...)

Add some asserts, if you like. We do have new stuff in 24.0 https://docs.galaxyproject.org/en/latest/dev/schema.html#assertions-for-image-data

**Comment by npinter** [comment]
> > Exception: Test output defines nothing to check (e.g. must have a 'file' check against, assertions to check, metadata or checksum tests, etc...)
> 
> Add some asserts, if you like. We do have new stuff in 24.0 https://docs.galaxyproject.org/en/latest/dev/schema.html#assertions-for-image-data

mmh looks like it doesn't work for output collection elements

.. ERROR: Test 1: unknown assertion 'has_image_width'
.. ERROR: Test 1: unknown assertion 'has_image_width'

**Comment by bgruening** [comment]
I think it will work when we update the testing to use 24.0. Working on it.

**Comment by bgruening** [comment]
Please rebase: https://github.com/galaxyproteomics/tools-galaxyp/commit/8e3a5e146a3e7a020a49a0f77c4718cbf364468b

The new image tests will work now.

**Pull request closed without merging**
