### PR TITLE
filter_by_fasta_id: speedup by using set

### PR DESCRIPTION
**Pull request by bernt-matthias**
For longer id lists the tool was horribly slow. I suggest to use `set` instead of `list` to store the ID list which speeds up the calculations dramatically and should not hurt in other respects.

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Failing test seems unrelated.

**Comment by bgruening** [comment]
Was ist denn das für ein Fehler, narf ...

**Comment by pravs3683** [comment]
I would also suggest using dictionaries (by making accession ids as key and
its corresponding sequence, including header, as values). This makes it
much faster.

**Comment by bernt-matthias** [comment]
@pravs3683 thanks for the suggestion, but I don't see how this could help.

**Comment by bernt-matthias** [comment]
hooray

**Comment by bgruening** [comment]
@pravs3683 the set() should not be slower then a dict() right?
I'm going to megre this.

Thanks @bernt-matthias!

**Comment by bernt-matthias** [comment]
Thanks @bgruening . Has galaxyp an automatic upload to the toolshed?

**Comment by bgruening** [comment]
Yes. But the packages failed to upload on master. So I pushed manually this time. Check again.

**Pull request merged**
