### PR TITLE
*tol_units changed form 1/2 to 1/0

### PR DESCRIPTION
**Pull request by bernt-matthias**
fixes https://github.com/galaxyproteomics/tools-galaxyp/issues/135

According to https://github.com/compomics/searchgui/wiki/ReleaseNotes this changed back in SearchGUI 2.8.0

Please note that also with this fix the GTN metaproteomics tutorial does in the peptideshaker step.

### CODE REVIEW

**Comment by bgruening** [comment]
We should probably increase the version number of this tool?

**Comment by bernt-matthias** [comment]
I think that it would be a good idea to add the GTN tutorial data as a test case, since it would be really great if the GTN tutorials would just work :)

**Comment by bernt-matthias** [comment]
Jep we could, but this would require quite a bit of modifications to the tool, e.g.:

Changes in SearchGUI 3.2.15 (May 8. 2017):
    FEATURE IMPROVEMENT: Added "Dimethylation of K 2H4" to the standard list of PTMs.

Probably there are more. 

I'm sure that I'm not experienced enough with this tool to do such changes.

**Comment by bgruening** [comment]
We will soon run all tutorials and there workflows weekly to test them, and catch errors early one.

@bernt-matthias what I mean is not increasing the requirement, just bump the tool version. So this line https://github.com/bernt-matthias/tools-galaxyp/blob/8b0e5d96f02d44e191cad12d15455b2ba46613b6/tools/peptideshaker/searchgui.xml#L1 to .2 and the peptideshaker one as well.

**Comment by bernt-matthias** [comment]
@bgruening got it..  and excellent idea to run regular test of the tutorials

**Comment by bgruening** [comment]
Damn, forgot about this one. Will fix the test tomorrow and merge. 
Sorry Mathias!

**Pull request merged**
