### PR TITLE
Pathwaymatcher publication

### PR DESCRIPTION
**Pull request by CarlosHorro**
Just updated link to the final version of Gigascience paper:
DOI: 10.1093/gigascience/giz088

### CODE REVIEW

**Comment by CarlosHorro** [comment]
It would be also great if this version replace the one currently installed at
https://usegalaxy.eu/

as 1)this one will probably be the last one for some time, 2)it references the final publication and 3)options mentioned in the paper as the ACCESION match criteria are available here.

**Comment by bgruening** [comment]
Thanks @CarlosHorro! Installed at https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/galaxyp/reactome_pathwaymatcher/reactome_pathwaymatcher/1.9.1.3

**Comment by bgruening** [comment]
You are welcome to contribute a small blog post if you like to advertise your tool at usegalaxy.eu here: https://galaxyproject.eu/freiburg/news

You can create a PR here https://github.com/usegalaxy-eu/website or just mail me the sentence.

**Comment by CarlosHorro** [comment]
> You are welcome to contribute a small blog post if you like to advertise your tool at usegalaxy.eu here: https://galaxyproject.eu/freiburg/news
> 
> You can create a PR here https://github.com/usegalaxy-eu/website or just mail me the sentence.

Great, thank you! I will work on it and send you the text as soon as possible :-)

**Pull request merged**
