### PR TITLE
Update Bumbershoot to 3.0.21142-0e4f4a4

### PR DESCRIPTION
**Pull request by chambm**

### CODE REVIEW

**Comment by chambm** [comment]
I'm not sure why temp_directory_path is failing now. It hasn't changed in this update, so I guess the test environment has changed. @bgruening What Docker container should I launch so I can repro the failure?

**Comment by bgruening** [comment]
That one here: https://quay.io/repository/biocontainers/bumbershoot?tag=latest&tab=tags

**Comment by chambm** [comment]
So it must have something to do with how /tmp is mounted with Planemo. Running the test with that Docker container in an isolated way doesn't fail, i.e.:
```
docker run -it --rm quay.io/biocontainers/bumbershoot:3_0_21142_0e4f4a4--h7d875b9_0 bash
cd /tmp
wget https://github.com/galaxyproteomics/tools-galaxyp/raw/7f162a87697350e03ac0179187b138fb48cc98cc/tools/bumbershoot/test-data/201208-378803-mm.idpDB
wget https://github.com/galaxyproteomics/tools-galaxyp/raw/7f162a87697350e03ac0179187b138fb48cc98cc/tools/bumbershoot/test-data/201208-378803-msgf.idpDB
wget https://github.com/galaxyproteomics/tools-galaxyp/raw/7f162a87697350e03ac0179187b138fb48cc98cc/tools/bumbershoot/test-data/201208-378803-cm.idpDB
idpAssemble -MaxFDRScore 0.05 -MinDistinctPeptides 2 -MinSpectra 2 -MinAdditionalPeptides 1 -MinSpectraPerDistinctMatch 1 -MinSpectraPerDistinctPeptide 1 -MaxProteinGroupsPerPeptide 10 -SummarizeSources 1    -MergedOutputFilepath output *.idpDB
```

I vaguely recall we ran into something like this before, but don't remember if it's exactly the same issue or how we worked past it.  The Galaxy and/or planemo log really ought to include the docker command used to launch containers.

**Comment by bgruening** [comment]
@chambm please run planemo with `--no_clearnup` and inspect the job_working_dir ... it will provide you the entire Docker command. We could save this as part of our CI artefacts I guess.

**Comment by chambm** [comment]
@bgruening Do you think most Galaxy setups will have _GALAXY_JOB_TMP_DIR equally performing as /tmp?

**Comment by bgruening** [comment]
Yes I would assume so. Galaxy respects $TEMP and this defaults on most systems to /tmp I assume.

**Comment by bgruening** [comment]
@chambm alternative idea. Can you please add a recent `profile="20.01"` to your tool? This will change the tmp behaviour I think.

**Comment by bgruening** [comment]
Leave the profile even if its does not work. Its better! :)

**Comment by chambm** [comment]
OK, but I realized 20.01 would actually exclude the instance I'm trying to install it in, because of  https://github.com/bgruening/docker-galaxy-stable/issues/575 ;)

**Comment by chambm** [comment]
Blarg! On my 19.09 instance I get this error now:
`boost::filesystem::copy_file: Read-only file system: "/export/galaxy-central/database/files/000/dataset_108.dat", "/export/galaxy-central/database/job_working_directory/000/88/tmp/81acf41b994de803.idpDB"`

```
sudo docker run -e "GALAXY_SLOTS=$GALAXY_SLOTS" -e "HOME=$HOME" -e "_GALAXY_JOB_HOME_DIR=$_GALAXY_JOB_HOME_DIR" -e "_GALAXY_JOB_TMP_DIR=$_GALAXY_JOB_TMP_DIR" -e "TMPDIR=$TMPDIR" -e "TMP=$TMP" -e "TEMP=$TEMP" --name 6199f585f8b2434c91833ecdce086aa0 \
-v /galaxy-central:/galaxy-central:ro \
-v /galaxy-central/database/shed_tools/toolshed.g2.bx.psu.edu/repos/galaxyp/idpassemble/4b418a632bb0/idpassemble:/galaxy-central/database/shed_tools/toolshed.g2.bx.psu.edu/repos/galaxyp/idpassemble/4b418a632bb0/idpassemble:ro \
-v /export/galaxy-central/database/job_working_directory/000/88:/export/galaxy-central/database/job_working_directory/000/88:ro \
-v "$_GALAXY_JOB_HOME_DIR:$_GALAXY_JOB_HOME_DIR:rw" \
-v /export/galaxy-central/database/job_working_directory/000/88/working:/export/galaxy-central/database/job_working_directory/000/88/working:rw \
-v /export/galaxy-central/database/files:/export/galaxy-central/database/files:rw -w /export/galaxy-central/database/job_working_directory/000/88/working \
--rm --memory 14G -e _JAVA_OPTIONS="-Xmx14G" --user 1450:1450 quay.io/biocontainers/bumbershoot:3_0_21142_0e4f4a4--h7d875b9_0 /bin/bash /export/galaxy-central/database/job_working_directory/000/88/tool_script.sh > ../tool_stdout 2> ../tool_stderr; return_code=$?; if [ -f /export/galaxy-central/database/job_working_directory/000/88/working/output ] ; then cp /export/galaxy-central/database/job_working_directory/000/88/working/output /export/galaxy-central/database/files/000/dataset_114.dat
```
Isn't `/export/galaxy-central/database/job_working_directory/000/88` and `$_GALAXY_JOB_HOME_DIR` the same thing? It's getting mounted as readonly first and then as readwrite, I'm not sure which would would take precedence. But I don't see tmp being mounted at all, so I assume the parent directory's ro/rw mode is inherited. This is a pretty stock Galaxy docker setup. I didn't give it any environment variables to change temp behavior.

**Comment by chambm** [comment]
Solved by adding to docker_extra_arguments: `-v "$_GALAXY_JOB_TMP_DIR:$_GALAXY_JOB_TMP_DIR:rw"`

But should this be necessary @bgruening ?

**Pull request merged**
