### PR TITLE
remove proteomic datatypes

### PR DESCRIPTION
**Pull request by bgruening**
These should be included in newer Galaxy releases.

### CODE REVIEW

**Comment by bgruening** [comment]
@jj-umn can we remove the proteomics datatypes? They should be included in Galaxy now, isn't it?

**Comment by bgruening** [comment]
ping @jj-umn @iracooke

**Comment by iracooke** [comment]
Hi @bgruening this is most likely fine but I am not the maintainer of those repos so I cant be 100% sure.  I believe almost everything in the old proteomics datatypes is now in the main galaxy distribution but in theory it is possible this might break stuff.

**Comment by bgruening** [comment]
I would like enforcing the removal of all datatypes and if anything is missing we should fix it asap in Galaxy.
Just to stick to the best-practice-guidelines.

**Comment by bgruening** [comment]
Let's merge it. All datatypes should be in Galaxy and we should enforce this as community.

**Pull request merged**
