### PR TITLE
update version

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
@CarlosHorro if you release a new version with your fix we can bump it as well.

**Comment by CarlosHorro** [comment]
> @CarlosHorro if you release a new version with your fix we can bump it as well.

Yep, I suppose I will have to wait until a new version of ThermoRawFileParser is launched and its conda package ready. ..
Of course I will update the ThermoRawFileConverter galaxy tool in order to link to the last app version.

**Comment by CarlosHorro** [comment]
Really fast! :-)

**Comment by bgruening** [comment]
Enjoy!

**Pull request merged**
