### PR TITLE
pyprophet updates

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
Hi @galaxyproteomics/developers anyone has time to help here :)

**Comment by bgruening** [comment]
* add tests
* adopt to new parameters and new IUC standards
* add .shed.yml

**Comment by jj-umn** [comment]
@bgruening   With osw datatype released in 19.09, should this now be merged?   Should this tool version require galaxy release 19.09 in the tool to guarantee availability of sow datatype?

**Comment by bgruening** [comment]
@jj-umn unfortunately I never had time to finish this update. The tool has a lot more parameters and so on.... we should update it properly before we merge, add tests etc ...

**Pull request closed without merging**
