### PR TITLE
Fix symlinking of collection files.

### PR DESCRIPTION
**Pull request by reid-wagner**
After updating the initial PR to replace certain characters in input filenames, I failed to retest the collection input logic (MetaNovo can run on multiple files), and it was broken.

This makes a good case for adding automated tests soon.

### CODE REVIEW

**Comment by bgruening** [comment]
@reid-wagner why are those error not catched by the tests?

**Comment by reid-wagner** [comment]
@bgruening - there are no tests yet. I am writing some now.

**Comment by bgruening** [comment]
Oo, those PRs should not be merged without tests :-(

Thanks for writing them!

**Comment by reid-wagner** [comment]
Ah sorry, I figured because the checks didn't error out that it was acceptable.

**Pull request merged**
