### PR TITLE
filter_by_fasta_ids: let the user specify whether to remove duplicate sequences

### PR DESCRIPTION
**Pull request by nsoranzo**
Also:
- Move tool files to main dir to ease testing with Planemo
- Add tests
- Print messages on stdout instead of (not returned) log file
- Python flake8 fixes
- Remove unused `tool-data` directory

### CODE REVIEW

**Comment by bgruening** [comment]
Looks good to me. I really need to get testing done here as well.
xref: https://github.com/galaxyproteomics/tools-galaxyp/pull/58

Thanks @nsoranzo!

**Comment by nsoranzo** [comment]
Thanks for the merge @bgruening! I have preserved backward compatibility but added a new parameter, so you may want to increase the version number before uploading to the ToolShed.

**Comment by bgruening** [comment]
Thanks for letting me know. I think it's fine as it is!

**Comment by nsoranzo** [comment]
@bgruening Hmm, after updating the tool is not found by Galaxy because it was moved from tools/ to the main directory:
```
Error reading tool configuration file from path: toolshed.g2.bx.psu.edu/repos/galaxyp/filter_by_fasta_ids/463ebeccb854/filter_by_fasta_ids/tools/filter_by_fasta_ids.xml.
```
I had to manually modify `config/shed_tool_conf.xml` to read:
```
<tool file="toolshed.g2.bx.psu.edu/repos/galaxyp/filter_by_fasta_ids/463ebeccb854/filter_by_fasta_ids/filter_by_fasta_ids.xml" guid="toolshed.g2.bx.psu.edu/repos/galaxyp/filter_by_fasta_ids/filter_by_fasta_ids/1.0">
```
Any idea how to solve this cleanly?

**Comment by bgruening** [comment]
The only thing I can imagine is to reset metadata, which I just did. But this smells a lot like a Galaxy bug. 
We need to change the folders as soon as possible to stick to our standards. I think @peterjc blast tools have also some non-standard folder hierarchy.

**Comment by peterjc** [comment]
Is this basically a mirror of my code? If so you're free to adjust the folder structure as required...

**Pull request merged**
