### PR TITLE
Let's go without ö.

### PR DESCRIPTION
**Pull request by bgruening**
This will probably couse some trouble down-stream. Like not rendering in the TS :)

### CODE REVIEW

**Comment by bgruening** [comment]
ping @jj-umn

**Comment by glormph** [comment]
Is it only necessary in the <description> tag? Otherwise there are some more umlauts in the help texts. Also, I know +e is the way to go in German, but I think these are supposed to be "hardrock-umlauts" which are not pronounced. Don't ask me why, but what the command line interface does is to just strip them:
http://cruxtoolkit.sourceforge.net/hardklor.html

**Comment by bgruening** [comment]
@glormph I have changed it thanks. I hope this is enough. Help text can be rendered afaik. It's just the name that ends up in all places were I'm not sure about the consequences :)

**Comment by jj-umn** [comment]
@glormph @bgruening   I didn't want to question the alphabet, having been raised with a diacritically-challenged language.

**Comment by bgruening** [comment]
@jj-umn thanks for the merge!

**Pull request merged**
