### PR TITLE
Fixed Msgf custom modification with multiple aa_specificities

### PR DESCRIPTION
**Pull request by Stortebecker**
Hi.
Our MSGF+ wrapper had a bug when using custom mods with more than one `aa_specificity`. I fixed this and adapted the last test accordingly. Instead of comparing the diff, the test looks for the identification of the custom mods now.
Cheers, Flo

P.S.: My first steps into Python/Cheetah!

### CODE REVIEW

**Comment by Stortebecker** [comment]
Why did the Travis-test fail? I cannot see the error. Can somebody please help?

**Comment by glormph** [comment]
I think it may be the same problem as in #204. @bgruening has pinged @chambm about incorrect test-data I think.

Otherwise, the PR looks good to me!

**Comment by chambm** [comment]
The change to the test to only check for the mod strings is quite a bit less stringent. If, for some strange reason, everything else about the file broke but the mods were right it would still pass. :) Can we assert both unchanged (+/- 6 lines) and also assert contents?

**Comment by bgruening** [comment]
restarted the tests.

**Comment by bgruening** [comment]
Cool, thanks a lot @Stortebecker!

**Comment by bgruening** [comment]
@chambm upps just saw your comment now.
@Stortebecker would be nice if you can address this in a follow up PR.

**Pull request merged**
