### PR TITLE
Update dbbuilder.xml

### PR DESCRIPTION
**Pull request by pravs3683**
cRAP database from TheGPM link is not working. Updated temporarily with a downloaded version of cRAP, shared form my github account.

### CODE REVIEW

**Comment by bgruening** [comment]
@pravs3683 maybe you can put it in here? https://github.com/galaxyproject/cargo-port
This link should be stable then.

Thanks!

**Comment by bgruening** [comment]
I also spotted that some tests are missing, if you have some time a test would be great.

**Comment by chambm** [comment]
@PratikDJagtap This breaks our proteogenomic workflows. I can't actually find any news about why the GPM FTP is requiring a username and password now. The obvious username "anonymous" doesn't work. I also realized that downloading the latest cRAP database every time compromises our workflows' repeatability. We should have some version control over that...

**Comment by PratikDJagtap** [comment]
Hello Matt,

We are working on resolving this.

Regards,
Pratik

Pratik Jagtap,

Research Assistant Professor, Department of Biochemistry, Molecular Biology
and Biophysics, University of Minnesota. *Address: 7-166 MCB, 420
Washington Ave SE, Minneapolis, MN 55455 **Phone: 612-624-0381
<http://612-624-0381/>    Email: pjagtap@umn.edu <pjagtap@umn.edu>   *

*http://galaxyp.org/ <http://galaxyp.org/>      *

**Comment by bgruening** [comment]
@pravs3683 there are some very small details that still prevents it from being tested I think. If you don't have time let me know and I will merge it and fix it afterwards.

- the dbbuilder.xml file should be next to the shed.yml file.
- the .shed.yml file should be enhanced with more metadata

**Comment by pravs3683** [comment]
Yeah. I think that will be okay. You can merge it now. And we can fix that
0art later.

**Comment by PratikDJagtap** [comment]
Hello Matt,

Sorry for a short reply earlier (was in a meeting). Here is a more detailed
reply:

There are two ways that we are trying to address this:

a) *Short-term plans*: We are changing the workflows to include ability to
download the cRAP database from a Custom URL (
https://raw.githubusercontent.com/pravs3683/cRAP/master/cRAP_protein_database.fasta).
This takes in the cRAP dB from 'pre-password era of theGPM dB' and
workflows seem to work fine.

b) *Long-term plans*: What Praveen has requested in this github issue is to
replace the cRAP (contaminants) dB link with the above link so that users
can download the CRAP dB without using the password.

I am also a bit perplexed on why cRAP dB needs a password now.

Regards,
Pratik

Pratik Jagtap,

Research Assistant Professor, Department of Biochemistry, Molecular Biology
and Biophysics, University of Minnesota. *Address: 7-166 MCB, 420
Washington Ave SE, Minneapolis, MN 55455 **Phone: 612-624-0381
<http://612-624-0381/>    Email: pjagtap@umn.edu <pjagtap@umn.edu>   *

*http://galaxyp.org/ <http://galaxyp.org/>      *

**Comment by pravs3683** [comment]
Hello Matt,

The dbbuilder is now updated on toolshed with the cRAP database (116
protein sequences) being downloaded from my github. You can
update dbbuilder (0.2.1) in your galaxy instance, and it should work fine.

Thanks,
Praveen

**Comment by chambm** [comment]
Pratik what's the difference between the short and long term you mention? Part a) is downloading a URL directly, part b) is updating dbbuilder to download from the same URL? It seems Praveen has already done that, right? But will that file be updated without any change to the URL? GitHub does seem perfectly appropriate for a small contaminants FASTA, btw. It will be easy to track changes to the FASTA, and we can refer to a specific version like: 
[https://raw.githubusercontent.com/pravs3683/cRAP/3c64f9580c8974ce7668ba0932aa982f04b1c681/cRAP_protein_database.fasta](https://raw.githubusercontent.com/pravs3683/cRAP/3c64f9580c8974ce7668ba0932aa982f04b1c681/cRAP_protein_database.fasta)
I may submit a PR for dbbuilder to have a "Latest" (master) option and an explicit list of cRAP versions (right now just the one).

**Comment by PratikDJagtap** [comment]
Hello Matt,

We now have both the options. The latest version available on toolshed can
download the CRAP dB from Praveen's github URL.

It will be a good idea to have the "latest" version of cRAP dB (and options
to access earlier versions) - though I am not sure if cRAP from theGPM ever
gets updated. Can you see if the password protected cRAP dB is different
than one via Praveen's github link?

Regards,
Pratik

Pratik Jagtap,

Research Assistant Professor, Department of Biochemistry, Molecular Biology
and Biophysics, University of Minnesota. *Address: 7-166 MCB, 420
Washington Ave SE, Minneapolis, MN 55455 **Phone: 612-624-0381
<http://612-624-0381/>    Email: pjagtap@umn.edu <pjagtap@umn.edu>   *

*http://galaxyp.org/ <http://galaxyp.org/>      *

**Pull request merged**
