### PR TITLE
WIP: openms 2.4

### PR DESCRIPTION
**Pull request by bernt-matthias**
So far only reproduce generation of 2.3 wrappers...

TODOs: 
- [ ] switch from 2.3 to 2.4
- [ ] https://github.com/galaxyproteomics/tools-galaxyp/issues/266
- [ ] `prepare_test_data.sh` uses ini files which sets parameters, either ignore it or extract parameters
- [ ] some more todos currently in generate.sh 
- [ ] some tools have output flags accepting multiple files that are in 1:1 correspondence with **an** input flag (FileMerger.ctd MapAlignerIdentification.ctd MapAlignerIdentification.ctd MapAlignerPoseClustering.ctd MapAlignerPoseClustering.ctd MapAlignerSpectrum.ctd MapAlignerSpectrum.ctd SeedListGenerator.ctd SpecLibSearcher.ctd SpectraSTSearchAdapter.ctd)
   - [ ] create output dir
   - [ ] generate output names with a for loop over the input
   - [ ] detect outputs in a collection
- [ ] re add IDMerger logic (select_merge ...), MapAligner* logic
- [ ] read extra logic/edits in  MetaproSIP MzMLSplitter SequenceCoverageCalculator  postprocessing
- [ ] fixid tool id diffs (eg LowMemPeakPickerHiResRandomAccess)
- [ ] true for bool param in FeatureFinderMetabo
- [ ] remove sanitizers from selects (FeatureFinderMetabo) and data (IDMerger,MetaProSIP)
- [ ] PepNovoAdapter currently not generated (because of `-models` parameter). models should go to bioconda recipe or data manager needed. bioconda recipe: also fix version currently mismatch between download and version)
- [ ] proteinquantifier `param_peptide_out` needs proper naming to differentiate it from `param_out` 
      Xtandem has `param_xml_out` -> generalize CTDConverter 
- [ ] idposteriorerrorprobability outputs plot file which is a gnuplot file -> pipe through gnuplot and generate actual plot
- [ ] AssayGeneratorMetabo `command not found` (online docs is for call to SiriusAdapter???)
- [ ] tests
  - [ ] set format of inputs (or improve the sniffer logic of Galaxy)
- [ ] fix tool version
- [ ] add missing data types (novor, sqmass, kroenik, cachedmzml, dta, peplist, fid, dta2d, paramxml) https://github.com/galaxyproject/galaxy/pull/8109
- [ ] some tools have defaults (for files) in the ctd that are located somewhere in the env https://github.com/OpenMS/OpenMS/issues/4361

### CODE REVIEW

**Comment by bernt-matthias** [comment]
ping @bgruening just felt like starting to work on this. aim is a fully automatic script and tests. still in the beginning .. aka a good time for collecting ideas. 

@jvolkening in https://github.com/galaxyproteomics/tools-galaxyp/issues/266 you mentioned that you could come up with a list of tools that use threads. would be helpful here.

**Comment by bgruening** [comment]
@bernt-matthias can you call me tomorrow I have a few things in mind for this.

**Comment by foellmelanie** [comment]
Hi @bernt-matthias 
these are the errors I found: 

- many tools: `cannot find 'element_identifier' while searching for 'param_db_struct.element_identifier' `
- AssayGeneratorMetabo: `AssayGeneratorMetabo: command not found`
- CompNovoCID: precursor_peak_tolerance = precursor_mass_tolerance in header line of idXML
- many tools: ` cannot find 'adv_opts'`
- ExternalCalibration and InternalCalibration: `Error creating a job for these tool inputs - A real number is required`
- ExternalCalibration: Repeat does not make sense here
- FeatureFinderIdnetification: `cannot find 'param_candidates_in'`
- HighResPrecursorMassCorrector: Last test: `Cannot read input file given from parameter '-feature:in'`
- IDFileConverter:
    - Test4: `Error: Could not determine output file type`
    - Test3,6-13,15-19,22-25: `Cannot read input file given from parameter '-mz_file'!`
    - Test14: Allow 2 lines diff for idXML output
    - Test21: many lines differ
- FileFilter:
    - Test 1-9,11-41,43-49: ln: failed to create symbolic link 'None.data': File exists
    - Test 10: An invalid option was selected for param_spectra_remove_activation, u'Collision'
    - Test42:An invalid option was selected for param_spectra_select_polarity, u'-spectra_select_polarity'
- IDFilter:
    - Test1-19,23: `ln: failed to create symbolic link 'None.data': File exists`
    - Test20-22: `An invalid option was selected for param_missed_cleavages_enzyme, u'Lys'`
- IDMapper: `Cannot read input file given from parameter '-spectra:in'!`
- MetaProSIP: Conda R-version 3.3.1 and OpenMS2.4 are in conflict
- MRMTransitionGroupPicker: `Parameters passed to 'MRMTransitionGroupPicker' are invalid`
- MSstatsConverter: `cannot find 'param_reannotate_filenames'`
- OpenPepXLLF: `cannot find 'param_decoy_database'`
- OpenPepXL: `cannot find 'param_decoy_database'`
- OpenSwathConfidenceScoring: test inputfile OpenSwathConfidenceScoring_1_output.tmp is missing
- OpenSwathWorkflow: `cannot find 'param_swath_windows_file'`

**Comment by bernt-matthias** [comment]
superseded by https://github.com/galaxyproteomics/tools-galaxyp/pull/415

**Pull request closed without merging**
