### PR TITLE
remove megahit

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
ping @jraysajulga

**Comment by jraysajulga** [comment]
Bye bye MEGAHIT. Thanks!

**Comment by bgruening** [comment]
I have also deprecated the galaxyp version on the TS. @jraysajulga we need to be more careful where we put those tools. As background info, a Galaxy tool has an ID, consisting out of a triplet - toolshed + owner + tool-id.

As soon as we change one of those three, Galaxy will not recognize it as one and the same tool and hence you will see two tools in the toolbar and in workflows the tool can not be updated from one version to the other.

**Comment by jraysajulga** [comment]
Thanks and agreed... I've seen a lot of "duplicate" tools as a result of those differences.

**Pull request merged**
