### PR TITLE
Msproteomicstools

### PR DESCRIPTION
**Pull request by bgruening**
Initial work on msproteomicstools and PeptideShaker updates.

### CODE REVIEW

**Comment by bgruening** [comment]
Initial work on msproteomicstools and PeptideShaker updates.

**Comment by trevor** [comment]
Thanks!

I'll merge this, but had a quick question. I see package_python_2_7 is required for package_msproteomicstools_0_3_2 and package_pyprophet_0_13_2. Do you know what the current blockers are to (finally...) moving to Python 3 for some of these?

**Comment by bgruening** [comment]
I'm not sure this works under python3 in the readme I only found `Python >= 2.5`. So I thought this would be save.

**Comment by trevor** [comment]
Unrelated to your pull request, but yes it looks like both msproteomicstools and pyprophet need some work to be brought up to modern version of Python.


### For pyprophet

* Uses outdated version of NumPy API:

      "Using deprecated NumPy API, disable it by "


* The pip package doesn't have numpy as a dependency, so it needs to be manually installed:

      `pip install pyprophet` =>  `ImportError: No module named 'numpy'`


* Doesn't support Python 3 syntax:

  ```
  Installing pyprophet script to /usr/local/bin
    File "/usr/local/lib/python3.4/site-packages/pyprophet/main.py", line 26
      print "usage:"
                   ^
  SyntaxError: Missing parentheses in call to 'print'

    File "/usr/local/lib/python3.4/site-packages/pyprophet/pyprophet.py", line 30
      def unwrap_self_for_multiprocessing((inst, method_name, args),):
                                          ^
  SyntaxError: invalid syntax
  ```



### For msproteomicstools

* Doesn't support Python 3 syntax:

  ```
  Downloading/unpacking xlwt (from msproteomicstools)
    Downloading xlwt-0.7.5.tar.gz (115kB): 115kB downloaded
    Running setup.py (path:/private/var/folders/l2/f_sjcng56kl3ysgn0q4h36x40000gn/T/pip_build_jw/xlwt/setup.py) egg_info for package xlwt
      Traceback (most recent call last):
        File "<string>", line 17, in <module>
        File "/private/var/folders/l2/f_sjcng56kl3ysgn0q4h36x40000gn/T/pip_build_jw/xlwt/setup.py", line 4, in <module>
          from xlwt import __VERSION__
        File "/private/var/folders/l2/f_sjcng56kl3ysgn0q4h36x40000gn/T/pip_build_jw/xlwt/xlwt/__init__.py", line 3, in <module>
          from Workbook import Workbook
      ImportError: No module named 'Workbook'
  ```

**Comment by bgruening** [comment]
@trevor are you running Galaxy under Python3?

**Comment by trevor** [comment]
Not possible yet as far as I understand.

Tools run outside of the webserver env, and would rather only need to support modern dev tools if possible.

**Comment by bgruening** [comment]
I can bind every package to a specific python version.

**Pull request merged**
