### PR TITLE
Improved msgf custom mod testing

### PR DESCRIPTION
**Pull request by Stortebecker**
Improves the test on the custom mods as suggested here: https://github.com/galaxyproteomics/tools-galaxyp/pull/212

I had to replace the file tested against, as the cGMP mod is working now and occuring 66 times. @chambm Could you check, if `lines_diff="6"` is sufficient?

### CODE REVIEW

**Comment by chambm** [comment]
You forgot to change the output filename. I also suggest that you don't rename the file so we can compare the old one to the new one. The commit history will suffice to tell us when it was created (not sure why I put that datestamp in there to be honest).

**Comment by Stortebecker** [comment]
Hmpf. What did I forget now? Ah, I see. One minute.

**Comment by bgruening** [comment]
@Stortebecker can you please update the test data. We have now a new msgfplus version.

**Comment by Stortebecker** [comment]
@bgruening All right, schon fertig.

**Comment by bgruening** [comment]
Danke!

**Pull request merged**
