### PR TITLE
Msgf+ on mzml/fasta pairs

### PR DESCRIPTION
**Pull request by glormph**
Hi, our lab does quite a bit of MSGF+ searches using prefractionated databases matched with prefractionated spectra (by isoelectric point). We use our own MSGF+ tool XML but it would be nice if this could be in the toolshed instead. The tool takes as input either a spectra and a fasta dataset, or a dataset_collection of a pair of spectra/fasta.

There are 2 problems with this PR:
 + Breaks workflows/automation by moving the `params` inside a `conditional`
 + I cannot get the planemo tests to work (but the tool works inside galaxy)

### CODE REVIEW

**Comment by bgruening** [comment]
This is great! Can you elaborate one the two problems? The first one seems to be OK to me. You can use conditionals in workflows.
Do you have a error of the planemo failure?

**Comment by glormph** [comment]
I guess the first one is more if someone has a workflow/API automation and the tool is updated, the workflow will also need to be updated because the param names change.
Second point may depend on my setup. I am unfortunately not so used to `planemo test` yet. I get:

    RunToolException: Error creating a job for these tool inputs - History does not include a dataset of the required format / build, History does not include a dataset of the required format / build

I am not sure if this is actually message that comes after the real error/fail though.

**Comment by jj-umn** [comment]
UMN does have anybody using the existing MS-GF+ tool or workflows depending on it.   Currently, MS-GF+ is being used via SeaarchGUI.  
Unless someone else has a strong objection to this enhancement, I'd vote to merge it.

**Comment by tjgriff1** [comment]
It seems reasonable to merge and use MS-GF+ via SearchGUI

**Comment by glormph** [comment]
It is unlikely we are going to find a lot of people using this tool in a github PR. But yeah, it may break someone's workflow, but updates are at your own risk, test it first, etc I guess.
I see I have to condaify the msgfplus.xml also if I want to run `planemo test` using conda installed msgfplus.

**Comment by bgruening** [comment]
Yes it is possible to have both of all with a bash trick. You ask if this python wrapper exists, if not you use java -jar ... we have this in tools-iuc. Let me know if you need it.

**Pull request merged**
