### PR TITLE
Remove complete proteome set options.

### PR DESCRIPTION
**Pull request by wagnerr20**
This removes an unnecessary option in the dbbuilder tool.

### CODE REVIEW

**Comment by bgruening** [comment]
Hi @wagnerr20 - anything we can help?

**Comment by wagnerr20** [comment]
Hi @bgruening - I started last week with the MSI team. I was implementing this change as requested by @jj-umn.

I hadn't reconfigured git to use my new UMN email, as you can see in the commit. I closed this so it wouldn't be merged and created a new PR with the email correction as well as a version increment in #523.

**Comment by bgruening** [comment]
Ah I see, welcome to the team!!!

**Comment by wagnerr20** [comment]
Thanks!

**Pull request closed without merging**
