### PR TITLE
Update eggnog-mapper to 2.0.1

### PR DESCRIPTION
**Pull request by abretaud**
Following #486, here's the update of eggnog-mapper from 1.0.3 to 2.0.1.
As [hmm search is now deprecated](https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2#v200), I removed any trace of it.
I had to update the test sqlite db too, which was... not fun :) I'll post what I did to https://github.com/galaxyproteomics/egglet I think

### CODE REVIEW

**Comment by jj-umn** [comment]
@abretaud @bgruening  Thanks for all the work on this.  
 I was investigating why the tests were failing this morning.  The http://eggnog5.embl.de/download/emapperdb-5.0.0/eggnog.db and eggnog_mapper/test-data/cached_locally/eggnog.db have the version at "2.0":
```
$ sqlite3 eggnog.db
SQLite version 3.28.0 2019-04-15 14:49:49
Enter ".help" for usage hints.
sqlite> select * from version;
2.0
```

**Comment by jj-umn** [comment]
@abretaud @bgruening  There seems to be a problem with the layout of the repository.   When I run planemo test on each tool individually, they all pass.   But when I run planemo test on the repository, all three tools fail.   

> (planemo) $ planemo test
> planemo couldn't find a target test-data directory, you should likely create a test-data directory or pass an explicit path using --test_data.

**Comment by bgruening** [comment]
Does `planemo test .` work? With the`.`?

**Comment by jj-umn** [comment]
@bgruening @abretaud  These planemo test commands all pass on my local installation:

> planemo test eggnog_mapper/eggnog_mapper.xml
> planemo test data_manager_eggnog_mapper/data_manager/data_manager_eggnog.xml
> planemo test data_manager_eggnog_mapper_abspath/data_manager/data_manager_eggnog.xml
> 

However, if I just run planemo test then all three fail:

> planemo test

Any suggestions?

**Comment by bgruening** [comment]
@jj-umn the DOT is missing imho.

**Comment by jj-umn** [comment]
@bgruening @abretaud 

> (planemo) $ planemo test .
> ...
> Testing complete. HTML report is in "/Users/jj/gx/gh/gxp/tools-galaxyp/tools/eggnog_mapper/tool_test_output.html".
> There were problems with 5 test(s) - out of 5 test(s) executed. See /Users/jj/gx/gh/gxp/tools-galaxyp/tools/eggnog_mapper/tool_test_output.html for detailed breakdown.
> data_manager_eggnog[0]: failed
> data_manager_eggnog_abspath[0]: failed
> eggnog_mapper[0]: failed
> eggnog_mapper[1]: failed
> eggnog_mapper[2]: failed


(planemo) $ planemo test eggnog_mapper/eggnog_mapper.xml
Testing complete. HTML report is in "/Users/jj/gx/gh/gxp/tools-galaxyp/tools/eggnog_mapper/tool_test_output.html".
All 3 test(s) executed passed.
eggnog_mapper[0]: passed
eggnog_mapper[1]: passed
eggnog_mapper[2]: passed

**Comment by bgruening** [comment]
@jj-umn I can reproduce it, but I guess this is how planemo works. I have the problem that the 2 data managers still fail because they have 2.0 somewhere, but I can not find it :(

**Comment by abretaud** [comment]
> @abretaud @bgruening Thanks for all the work on this.
> I was investigating why the tests were failing this morning. The http://eggnog5.embl.de/download/emapperdb-5.0.0/eggnog.db and eggnog_mapper/test-data/cached_locally/eggnog.db have the version at "2.0":
> 
> ```
> $ sqlite3 eggnog.db
> SQLite version 3.28.0 2019-04-15 14:49:49
> Enter ".help" for usage hints.
> sqlite> select * from version;
> 2.0
> ```

The numbering is a bit exotic, it's eggnog-mapper db version 2.0, based on eggnog 5.0

**Comment by abretaud** [comment]
`download_eggnog_data.py: command not found` is weird, it is supposed to be installed just as `emapper.py`

**Comment by abretaud** [comment]
Maybe a bug in galaxy? Tested locally: the resolver does not find any container suitable to run the test, but removing the `tool_type="manage_data"` is enough to let the resolver find the good container (but fails later in the test process of course).
Any idea?

**Comment by bgruening** [comment]
Other data managers work for me. Maybe I oversee something but can it be that those data managers do download the data into the shed_tools/ folder instead of the data manager folder? `#set $install_path = $os.path.join($os.path.dirname($__tool_directory__), 'test-data/cached_locally')` ???

The tool seems to work. I also can run the data manager tests locally without hitting the error here.

**Comment by bgruening** [comment]
> Maybe a bug in galaxy? 

Can be, I con confirm this.

I also tested it locally and I will merge this now and push manually.

**Comment by bgruening** [comment]
> The numbering is a bit exotic, it's eggnog-mapper db version 2.0, based on eggnog 5.0

This is super confusing, how do we deal with this?

* is eggnog-mapper-db 2.0 working with eggnog-mapper 1.x and 2.x?
* we have the eggnog-mapper-db version previously labelled as 4.5 ... now its 2.0 so it looks older.

grafik

**Comment by bgruening** [comment]
```
diamond v2.0.4.142 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

#CPU threads: 1
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: /data/dnb03/galaxy_db/job_working_directory/011/269/11269845/working/emappertmp_dmdn_085Mfc
Opening the database...  [0.248s]
Error: Database was built with an older version of Diamond and is incompatible.
Traceback (most recent call last):
  File "/usr/local/tools/_conda/envs/__eggnog-mapper@2.0.1/bin/emapper.py", line 1213, in <module>
    main(args)
  File "/usr/local/tools/_conda/envs/__eggnog-mapper@2.0.1/bin/emapper.py", line 226, in main
    dump_diamond_matches(args.input, seed_orthologs_file, args)
  File "/usr/local/tools/_conda/envs/__eggnog-mapper@2.0.1/bin/emapper.py", line 380, in dump_diamond_matches
    raise e
subprocess.CalledProcessError: Command '/usr/local/tools/_conda/envs/__eggnog-mapper@2.0.1/bin/diamond blastp -d /data/db/data_managers/eggnog/4.5.1/eggnog_proteins.dmnd -q /data/dnb03/galaxy_db/files/7/0/2/dataset_7021213d-2c56-4aca-a74d-a9f3b209f663.dat --more-sensitive --threads 1 -e 0.001000 -o /data/dnb03/galaxy_db/job_working_directory/011/269/11269845/working/emappertmp_dmdn_085Mfc/1c441863aac5447ba5121b9547c55582 --top 3 --query-cover 0.0 --subject-cover 0.0' returned non-zero exit status 1

```

Oo.

So we need to add a version to the loc file and filter the loc file based on the tool combat version.

**Comment by abretaud** [comment]
Oh damn :( working on it

**Pull request merged**
