### PR TITLE
translate_bed

### PR DESCRIPTION
**Pull request by jj-umn**
Translate transcripts from the input BED file into protein sequences.
The genomic sequence:
  - may be supplied in an extra column in the BED input file
  - retrieved from a twobit genomic reference file
  - retrieved from the Ensembl REST API for Ensembl transcripts

### CODE REVIEW

**Comment by bgruening** [comment]
@jj-umn is this something that should be integrated into https://toolshed.g2.bx.psu.edu/repository?repository_id=5e1b70f8c4a31a72 ?

**Comment by jj-umn** [comment]
@bgruening Probably not part of extract_genomic_dna.  This is part of the workflow to generate proteomics search fasta databases from RNAseq data: fastq -> hisat2 -> StringTie -> gffCompare -> gffCompare_to_bed -> translate_bed.   The output contains both the protein fasta and a BED file with the genomic location of the protein.   Tom McGowan is close to having the MVP (Multiomic Visualization Plugin) done that will include a protein sequence viewer and a genomic viewer IGV.js that will be zoomed to exons of the protein being viewed.   The goal is to have IGV.js display RNAseq and proteomics outputs (proBAM files) concurrently.

**Comment by jj-umn** [comment]
@bgruening   The build failures include: 
The Galaxy client build is out of date.  Please run 'make client' or your choice of client build target (client-*).
Is that what is causing the build to fail?

**Comment by bgruening** [comment]
Very likely. We tested against dev and @dannon changed the dev branch to not ship client builds anymore.

**Comment by bgruening** [comment]
```
from builtins import str
ImportError: No module named builtins
```
Not Python2 compatible? I think you need to add the `future` module to the requirements.

**Pull request merged**
