### PR TITLE
Add LC_ALL setting to tool_dependencies for searchgui

### PR DESCRIPTION
**Pull request by iracooke**
@bgruening Can you check this to see if it looks right?

### CODE REVIEW

**Comment by bgruening** [comment]
Interesting. It's long time ago were I used this syntax, but it looks correct.

What about adding this line to the searchgui package?

```
 <environment_variable name="LC_ALL" action="set_to">C</environment_variable>
```

**Comment by iracooke** [comment]
Do you mean just add that line and then we would not need anything in tool_dependencies.xml?

That would be nice.  I'll try it later. I need to go to some talks now

**Comment by bgruening** [comment]
Yes, I guess this could work! Enjoy!

**Comment by iracooke** [comment]
I'm merging this now as it seems to work on my test

**Pull request merged**
