### PR TITLE
Update QuPath ROIsplitter to v0.3.2

### PR DESCRIPTION
**Pull request by npinter**
The update fixes a problem with the filling of ROIs.

### CODE REVIEW

**Comment by bgruening** [comment]
Please check your Python code, you are mixing tabs and spaces I think :)

Also the test is falling with:

> Expected file size of 459919+-0 found 1309478

Is the filesize change expected?

**Comment by npinter** [comment]
> Please check your Python code, you are mixing tabs and spaces I think :)
> 
> Also the test is falling with:
> 
> > Expected file size of 459919+-0 found 1309478
> 
> Is the filesize change expected?

I'm more of a tab guy :( I wasn't aware that this was a linting issue.

**Comment by bgruening** [comment]
Python guidelines. I recommend using [black](https://github.com/psf/black) and put this into your editor by default.

**Review by bgruening — APPROVED** [review]

**Comment by npinter** [comment]
ty! :)

**Pull request merged**
