### PR TITLE
MPA remove Xmx option

### PR DESCRIPTION
**Pull request by bernt-matthias**
alternatively the bioconda wrapper script should be adapted to
respect the environment variable

### CODE REVIEW

**Comment by bgruening** [comment]
It should respect those: https://github.com/bioconda/bioconda-recipes/blob/da52f05f3caac623e6d9cdd1a8e76afb424393f8/recipes/mpa-portable/mpa-portable.py

Isn't it?

**Comment by bernt-matthias** [comment]
> It should respect those: https://github.com/bioconda/bioconda-recipes/blob/da52f05f3caac623e6d9cdd1a8e76afb424393f8/recipes/mpa-portable/mpa-portable.py
> 
> Isn't it?

not if `-Xm*` is given on the command line: 

https://github.com/bioconda/bioconda-recipes/blob/da52f05f3caac623e6d9cdd1a8e76afb424393f8/recipes/mpa-portable/mpa-portable.py#L56

**Comment by bgruening** [comment]
Ah so you want to overwrite this variable with your own one? I see.

**Review by bgruening — APPROVED** [review]

**Comment by bernt-matthias** [comment]
Lets merge?

**Comment by bgruening** [comment]
@bernt-matthias please merge away if its accepted :)

**Pull request merged**
